config/routes.rb
Iot4Sample::Application.routes.draw do
  resources :vals


  resources :vals, only: [:index, :create]
end

app/models/val.rb
class Val < ActiveRecord::Base
  attr_accessible :p1, :p2, :p3, :p4, :p5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/vals_controller.rb
class ValsController < ApplicationController
  # GET /vals
  # GET /vals.json
  def index
    @vals = Val.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vals }
    end
  end

  # GET /vals/1
  # GET /vals/1.json
  def show
    @val = Val.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @val }
    end
  end

  # GET /vals/new
  # GET /vals/new.json
  def new
    @val = Val.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @val }
    end
  end

  # GET /vals/1/edit
  def edit
    @val = Val.find(params[:id])
  end

  # POST /vals
  # POST /vals.json
  def create
    ps = params[:val] || { p1: params[:p1], p2: params[:p2], p3: params[:p3], p4: params[:p4], p5: params[:p5],
                           p6: params[:p6], p7: params[:p7], p8: params[:p8], p9: params[:p9] }
    @val = Val.new(ps)

    respond_to do |format|
      if @val.save
        format.html { redirect_to @val, notice: 'Successfully created.' }
        format.json { render json: @val, status: :created, location: @val }
      else
        format.html { render action: "new" }
        format.json { render json: @val.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vals/1
  # PUT /vals/1.json
  def update
    @val = Val.find(params[:id])

    respond_to do |format|
      if @val.update_attributes(params[:val])
        format.html { redirect_to @val, notice: 'Val was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @val.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vals/1
  # DELETE /vals/1.json
  def destroy
    @val = Val.find(params[:id])
    @val.destroy

    respond_to do |format|
      format.html { redirect_to vals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vals_helper.rb
module ValsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iot4Sample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vals/_form.html.erb
<%= form_for(@val) do |f| %>
  <% if @val.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@val.errors.count, "error") %> prohibited this val from being saved:</h2>

      <ul>
      <% @val.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :p1 %><br />
    <%= f.text_field :p1 %>
  </div>
  <div class="field">
    <%= f.label :p2 %><br />
    <%= f.text_field :p2 %>
  </div>
  <div class="field">
    <%= f.label :p3 %><br />
    <%= f.text_field :p3 %>
  </div>
  <div class="field">
    <%= f.label :p4 %><br />
    <%= f.text_field :p4 %>
  </div>
  <div class="field">
    <%= f.label :p5 %><br />
    <%= f.text_field :p5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vals/edit.html.erb
<h1>Editing val</h1>

<%= render 'form' %>

<%= link_to 'Show', @val %> |
<%= link_to 'Back', vals_path %>

app/views/vals/index.html.erb
<h1>Listing vals</h1>

<table>
  <tr>
    <th>P1</th>
    <th>P2</th>
    <th>P3</th>
    <th>P4</th>
    <th>P5</th>
    <th>P6</th>
    <th>P7</th>
    <th>P8</th>
    <th>P9</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vals.each do |val| %>
  <tr>
    <td><%= val.p1 %></td>
    <td><%= val.p2 %></td>
    <td><%= val.p3 %></td>
    <td><%= val.p4 %></td>
    <td><%= val.p5 %></td>
    <td><%= val.p6 %></td>
    <td><%= val.p7 %></td>
    <td><%= val.p8 %></td>
    <td><%= val.p9 %></td>
    <td><%= link_to 'Show', val %></td>
    <td><%= link_to 'Edit', edit_val_path(val) %></td>
    <td><%= link_to 'Destroy', val, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Val', new_val_path %>

app/views/vals/new.html.erb
<h1>New val</h1>

<%= render 'form' %>

<%= link_to 'Back', vals_path %>

app/views/vals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>P1:</b>
  <%= @val.p1 %>
</p>

<p>
  <b>P2:</b>
  <%= @val.p2 %>
</p>

<p>
  <b>P3:</b>
  <%= @val.p3 %>
</p>

<p>
  <b>P4:</b>
  <%= @val.p4 %>
</p>

<p>
  <b>P5:</b>
  <%= @val.p5 %>
</p>


<%= link_to 'Edit', edit_val_path(@val) %> |
<%= link_to 'Back', vals_path %>